version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-fullstack_test}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-fullstack_test}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_LIFE: ${ACCESS_TOKEN_LIFE:-15m}
      REFRESH_TOKEN_LIFE: ${REFRESH_TOKEN_LIFE:-7d}
      RUN_MIGRATIONS: "true"
      RUN_SEEDS: "true"
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_API: http://localhost:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
